# Copyright (C) 2024 Ibrahem Mouhamad
#
# SPDX-License-Identifier: MIT

version: '3.3'

services:
  ci:
    image: ci
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - backend
    environment:
      CONTAINER_COVERAGE_DATA_DIR:
      GITHUB_ACTIONS:
      GITHUB_TOKEN:
      GITHUB_WORKSPACE:
      GITHUB_REF:
      GITHUB_HEAD_REF:
      GITHUB_RUN_ID:
    volumes:
      - ${HOST_COVERAGE_DATA_DIR}:${CONTAINER_COVERAGE_DATA_DIR}
